const scene=document.querySelector('#scene'),caption=document.querySelector('#caption'),back=document.querySelector('#back'),hint=document.querySelector('#hint'),fireEffects=document.querySelector('#fire-effects'),catEffects=document.querySelector('#cat-effects'),actionPanel=document.querySelector('#action-panel'),primaryAction=document.querySelector('#primary-action');
const things={books:{scale:1.9,x:10,y:31,text:'Books, old photos, and things nobody has thrown away.'},fire:{scale:2.18,x:24,y:60,text:'The fire settles into a slow, steady crackle.'},window:{scale:1.75,x:62,y:28,text:'Snow keeps falling beyond the glass.'},chair:{scale:1.65,x:54,y:58,text:'This looks like the correct place to disappear for a while.'},record:{scale:2,x:86,y:49,text:'The record player is waiting for something good.'},cat:{scale:2.35,x:88,y:76,text:'Fast asleep. Probably. One ear twitches when you get close.'}};
const order=['books','fire','chair','window','record','cat'],catLines=['A sleepy purr starts up under your hand.','One eye opens. You have been deemed acceptable.','The paw stretches out, then curls back into the blanket.','A tiny chirp. Apparently that was the correct spot.'];let focused=null,selected=-1,lastButtons=[],fireBusy=false,fireLevel=0,catPets=0,audioCtx=null;
function transformFor(t){const dx=(50-t.x)*(t.scale-1)/t.scale,dy=(50-t.y)*(t.scale-1)/t.scale;return `scale(${t.scale}) translate(${dx}%,${dy}%)`}
function focusThing(id){const t=things[id];focused=id;scene.style.transform=transformFor(t);document.querySelectorAll('.spot').forEach(s=>s.classList.toggle('active',s.dataset.id===id));caption.textContent=t.text;caption.classList.add('show');back.classList.add('show');hint.style.opacity=0;fireEffects.classList.toggle('show',id==='fire');catEffects.classList.toggle('show',id==='cat');actionPanel.classList.toggle('show',id==='fire'||id==='cat');if(id==='fire'){primaryAction.textContent=fireLevel>=3?'Fire is well tended':fireLevel?'Add another log':'Add a log';primaryAction.disabled=fireLevel>=3}else if(id==='cat'){primaryAction.textContent='Pet the cat';primaryAction.disabled=false}}
function reset(){focused=null;fireBusy=false;scene.style.transform='';document.querySelectorAll('.spot').forEach(s=>s.classList.remove('active'));caption.classList.remove('show');back.classList.remove('show');fireEffects.className='';catEffects.className='';actionPanel.classList.remove('show');primaryAction.disabled=false}
function select(i){selected=(i+order.length)%order.length;document.querySelectorAll('.spot').forEach(s=>s.classList.toggle('selected',s.dataset.id===order[selected]))}function move(dir){if(focused)return;if(selected<0)return select(0);select(selected+dir)}
function tendFire(){if(focused!=='fire'||fireBusy||fireLevel>=3)return;fireBusy=true;fireLevel=Math.min(fireLevel+1,3);primaryAction.disabled=true;primaryAction.textContent='Tending…';caption.textContent='You set another log onto the grate.';fireEffects.classList.add('tending');scene.classList.add('fire-surge');setTimeout(()=>{caption.textContent='The new wood catches. Heat rolls into the room.';fireEffects.classList.remove('tending');fireEffects.classList.add('surge')},850);setTimeout(()=>{scene.classList.remove('fire-surge');fireEffects.classList.remove('surge');fireEffects.classList.add('warm');caption.textContent=fireLevel>=3?'That should keep the cabin warm for a long while.':'The fire settles into a warmer, brighter crackle.';primaryAction.textContent=fireLevel>=3?'Fire is well tended':'Add another log';primaryAction.disabled=fireLevel>=3;fireBusy=false},3100)}
function purr(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),lfo=audioCtx.createOscillator(),lfoGain=audioCtx.createGain();osc.type='sine';osc.frequency.value=54;lfo.type='sine';lfo.frequency.value=24;lfoGain.gain.value=7;lfo.connect(lfoGain).connect(osc.frequency);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.035,now+.08);gain.gain.exponentialRampToValueAtTime(.0001,now+1.35);osc.connect(gain).connect(audioCtx.destination);osc.start(now);lfo.start(now);osc.stop(now+1.4);lfo.stop(now+1.4)}catch(e){}}
function petCat(){if(focused!=='cat')return;catPets++;caption.textContent=catLines[(catPets-1)%catLines.length];catEffects.classList.remove('pet');void catEffects.offsetWidth;catEffects.classList.add('pet');scene.classList.remove('cat-pet');void scene.offsetWidth;scene.classList.add('cat-pet');purr();setTimeout(()=>scene.classList.remove('cat-pet'),700)}
function interact(){if(focused==='fire')tendFire();else if(focused==='cat')petCat();else if(!focused){if(selected<0)select(0);focusThing(order[selected])}}
document.querySelectorAll('.spot').forEach(s=>{s.addEventListener('click',()=>focusThing(s.dataset.id));s.addEventListener('pointerenter',()=>{selected=order.indexOf(s.dataset.id)})});back.addEventListener('click',reset);primaryAction.addEventListener('click',interact);
addEventListener('keydown',e=>{if(e.key==='Escape'||e.key==='Backspace'){e.preventDefault();reset()}else if(['ArrowRight','ArrowDown','d','s'].includes(e.key)){e.preventDefault();move(1)}else if(['ArrowLeft','ArrowUp','a','w'].includes(e.key)){e.preventDefault();move(-1)}else if(e.key==='Enter'||e.key===' '){e.preventDefault();interact()}});
function pollGamepad(){const pads=navigator.getGamepads?.()||[];const p=[...pads].find(Boolean);if(p){const pressed=p.buttons.map(b=>b.pressed);const edge=i=>pressed[i]&&!lastButtons[i];if(edge(1))reset();else if(edge(0))interact();if(!focused&&(edge(12)||edge(14)))move(-1);if(!focused&&(edge(13)||edge(15)))move(1);lastButtons=pressed}else lastButtons=[];requestAnimationFrame(pollGamepad)}requestAnimationFrame(pollGamepad);setTimeout(()=>hint.style.opacity=0,6500);
